services:
  backend:
    build:
      context: ./studyspacebackend         
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb+srv://studyspace:studyspace@cluster0.ouluv.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=secret
      - GOOGLE_GENERATIVE_AI_API_KEY=AIzaSyCfojd6u-HFKtwEyid9mN9yZ7rq2Gev66I
      - FRONTEND_URL=http://localhost:4444
      - GOOGLE_CLIENT_ID=126043924205-0a6cf2igeg6etogf0a165sbfemu7nap7.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - GOOGLE_CALLBACK_URL=http://localhost:8080/api/auth/google/callback
    depends_on:
      - mongo

  frontend:
    build:
      context: ./edu        
      dockerfile: Dockerfile.frontend
    ports:
      - "4444:4444"
    depends_on:
      - backend

  mongo:
    image: mongo:6
    container_name: mongo_container
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
