# Build Stage
FROM node:18 as build
WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build  

# Production Stage
FROM nginx:alpine
COPY --from=build /usr/src/app/dist /usr/share/nginx/html

EXPOSE 4444
CMD ["nginx", "-g", "daemon off;"]
